---
- name: 'Elasticsearch for Debian & RedHat based servers'
  hosts: <YOUR-HOST-GROUP>
  become: yes

  tasks:
    - block:
      - name: 'Import the Elasticsearch GPG Key'
        rpm_key:
          state: present
          key: https://artifacts.elastic.co/GPG-KEY-elasticsearch
      - name: 'Add & update repository'
        yum_repository:
          name: elasticsearch
          description: Elasticsearch repository for 8.x packages
          file: elasticsearch
          baseurl: https://artifacts.elastic.co/packages/8.x/yum
          gpgcheck: yes
          gpgkey: https://artifacts.elastic.co/GPG-KEY-elasticsearch
          enabled: yes
      - name: 'Install elasticsearch'
        yum:
          update_cache: yes
          name: elasticsearch
          state: latest
      - name: 'Enable elasticsearch'
        systemd:
          name: elasticsearch
          enabled: yes
          daemon_reload: yes
      when: ansible_os_family == "RedHat"

    - block:
      - name: 'Import the Elasticsearch GPG Key'
        apt_key:
          url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
          state: present
      - name: 'Installing dependencies'
        apt:
          pkg:
            - ca-certificates
            - curl
            - apt-transport-https
          state: latest
          update_cache: true
      - name: 'Add repository'
        apt_repository:
          repo: deb https://artifacts.elastic.co/packages/8.x/apt stable main
          state: present
      - name: 'Install elasticsearch'
        apt:
          name: elasticsearch
          state: latest
          update_cache: yes
      - name: 'Enable elasticsearch'
        systemd:
          name: elasticsearch
          enabled: yes
          daemon_reload: yes
      when: ansible_os_family == "Debian"

